// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var webstreamer = webstreamer || {};

/**
 * @const
 * @namespace
 */
webstreamer.webrtc = webstreamer.webrtc || {};

/**
 * @const
 * @namespace
 */
webstreamer.webrtc.topics = webstreamer.webrtc.topics || {};

/**
 * @enum
 */
webstreamer.EndpointType = {
  RTSPCLIENT: 0,
  WEBRTC: 1
};

/**
 * @enum
 */
webstreamer.VideoCodec = {
  H264: 0,
  H265: 1,
  VP8: 2
};

/**
 * @enum
 */
webstreamer.AudioCodec = {
  PCMA: 0,
  OPUS: 1
};

/**
 * @constructor
 */
webstreamer.EndpointBase = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.EndpointBase}
 */
webstreamer.EndpointBase.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.EndpointBase=} obj
 * @returns {webstreamer.EndpointBase}
 */
webstreamer.EndpointBase.getRootAsEndpointBase = function(bb, obj) {
  return (obj || new webstreamer.EndpointBase).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.EndpointBase.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {webstreamer.EndpointType}
 */
webstreamer.EndpointBase.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {webstreamer.EndpointType} */ (this.bb.readInt8(this.bb_pos + offset)) : webstreamer.EndpointType.RTSPCLIENT;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.EndpointBase.startEndpointBase = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
webstreamer.EndpointBase.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {webstreamer.EndpointType} type
 */
webstreamer.EndpointBase.addType = function(builder, type) {
  builder.addFieldInt8(1, type, webstreamer.EndpointType.RTSPCLIENT);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.EndpointBase.endEndpointBase = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.RtspClient = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.RtspClient}
 */
webstreamer.RtspClient.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.RtspClient=} obj
 * @returns {webstreamer.RtspClient}
 */
webstreamer.RtspClient.getRootAsRtspClient = function(bb, obj) {
  return (obj || new webstreamer.RtspClient).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {webstreamer.EndpointBase=} obj
 * @returns {webstreamer.EndpointBase|null}
 */
webstreamer.RtspClient.prototype.base = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new webstreamer.EndpointBase).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.RtspClient.prototype.url = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.RtspClient.startRtspClient = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} baseOffset
 */
webstreamer.RtspClient.addBase = function(builder, baseOffset) {
  builder.addFieldOffset(0, baseOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} urlOffset
 */
webstreamer.RtspClient.addUrl = function(builder, urlOffset) {
  builder.addFieldOffset(1, urlOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.RtspClient.endRtspClient = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.Webrtc = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.Webrtc}
 */
webstreamer.Webrtc.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.Webrtc=} obj
 * @returns {webstreamer.Webrtc}
 */
webstreamer.Webrtc.getRootAsWebrtc = function(bb, obj) {
  return (obj || new webstreamer.Webrtc).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {webstreamer.EndpointBase=} obj
 * @returns {webstreamer.EndpointBase|null}
 */
webstreamer.Webrtc.prototype.base = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new webstreamer.EndpointBase).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.Webrtc.prototype.group = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.Webrtc.prototype.connection = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {webstreamer.webrtc.SdpRole}
 */
webstreamer.Webrtc.prototype.sdpRole = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? /** @type {webstreamer.webrtc.SdpRole} */ (this.bb.readInt8(this.bb_pos + offset)) : webstreamer.webrtc.SdpRole.OFFER;
};

/**
 * @returns {webstreamer.webrtc.StreamMode}
 */
webstreamer.Webrtc.prototype.audioStreamMode = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? /** @type {webstreamer.webrtc.StreamMode} */ (this.bb.readInt8(this.bb_pos + offset)) : webstreamer.webrtc.StreamMode.SENDONLY;
};

/**
 * @returns {webstreamer.webrtc.StreamMode}
 */
webstreamer.Webrtc.prototype.videoStreamMode = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? /** @type {webstreamer.webrtc.StreamMode} */ (this.bb.readInt8(this.bb_pos + offset)) : webstreamer.webrtc.StreamMode.SENDONLY;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.Webrtc.startWebrtc = function(builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} baseOffset
 */
webstreamer.Webrtc.addBase = function(builder, baseOffset) {
  builder.addFieldOffset(0, baseOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} groupOffset
 */
webstreamer.Webrtc.addGroup = function(builder, groupOffset) {
  builder.addFieldOffset(1, groupOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} connectionOffset
 */
webstreamer.Webrtc.addConnection = function(builder, connectionOffset) {
  builder.addFieldOffset(2, connectionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {webstreamer.webrtc.SdpRole} sdpRole
 */
webstreamer.Webrtc.addSdpRole = function(builder, sdpRole) {
  builder.addFieldInt8(3, sdpRole, webstreamer.webrtc.SdpRole.OFFER);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {webstreamer.webrtc.StreamMode} audioStreamMode
 */
webstreamer.Webrtc.addAudioStreamMode = function(builder, audioStreamMode) {
  builder.addFieldInt8(4, audioStreamMode, webstreamer.webrtc.StreamMode.SENDONLY);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {webstreamer.webrtc.StreamMode} videoStreamMode
 */
webstreamer.Webrtc.addVideoStreamMode = function(builder, videoStreamMode) {
  builder.addFieldInt8(5, videoStreamMode, webstreamer.webrtc.StreamMode.SENDONLY);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.Webrtc.endWebrtc = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.Endpoint = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.Endpoint}
 */
webstreamer.Endpoint.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.Endpoint=} obj
 * @returns {webstreamer.Endpoint}
 */
webstreamer.Endpoint.getRootAsEndpoint = function(bb, obj) {
  return (obj || new webstreamer.Endpoint).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {webstreamer.RtspClient=} obj
 * @returns {webstreamer.RtspClient|null}
 */
webstreamer.Endpoint.prototype.rtspclient = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new webstreamer.RtspClient).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {webstreamer.Webrtc=} obj
 * @returns {webstreamer.Webrtc|null}
 */
webstreamer.Endpoint.prototype.webrtc = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new webstreamer.Webrtc).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.Endpoint.startEndpoint = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} rtspclientOffset
 */
webstreamer.Endpoint.addRtspclient = function(builder, rtspclientOffset) {
  builder.addFieldOffset(0, rtspclientOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} webrtcOffset
 */
webstreamer.Endpoint.addWebrtc = function(builder, webrtcOffset) {
  builder.addFieldOffset(1, webrtcOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.Endpoint.endEndpoint = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.Pipeline = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.Pipeline}
 */
webstreamer.Pipeline.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.Pipeline=} obj
 * @returns {webstreamer.Pipeline}
 */
webstreamer.Pipeline.getRootAsPipeline = function(bb, obj) {
  return (obj || new webstreamer.Pipeline).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.Pipeline.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {webstreamer.VideoCodec}
 */
webstreamer.Pipeline.prototype.videoCodec = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {webstreamer.VideoCodec} */ (this.bb.readInt8(this.bb_pos + offset)) : webstreamer.VideoCodec.H264;
};

/**
 * @returns {webstreamer.AudioCodec}
 */
webstreamer.Pipeline.prototype.audioCodec = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {webstreamer.AudioCodec} */ (this.bb.readInt8(this.bb_pos + offset)) : webstreamer.AudioCodec.PCMA;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.Pipeline.startPipeline = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
webstreamer.Pipeline.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {webstreamer.VideoCodec} videoCodec
 */
webstreamer.Pipeline.addVideoCodec = function(builder, videoCodec) {
  builder.addFieldInt8(1, videoCodec, webstreamer.VideoCodec.H264);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {webstreamer.AudioCodec} audioCodec
 */
webstreamer.Pipeline.addAudioCodec = function(builder, audioCodec) {
  builder.addFieldInt8(2, audioCodec, webstreamer.AudioCodec.PCMA);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.Pipeline.endPipeline = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.LiveStreamCreate = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.LiveStreamCreate}
 */
webstreamer.LiveStreamCreate.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.LiveStreamCreate=} obj
 * @returns {webstreamer.LiveStreamCreate}
 */
webstreamer.LiveStreamCreate.getRootAsLiveStreamCreate = function(bb, obj) {
  return (obj || new webstreamer.LiveStreamCreate).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {webstreamer.Pipeline=} obj
 * @returns {webstreamer.Pipeline|null}
 */
webstreamer.LiveStreamCreate.prototype.pipeline = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new webstreamer.Pipeline).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {webstreamer.Endpoint=} obj
 * @returns {webstreamer.Endpoint|null}
 */
webstreamer.LiveStreamCreate.prototype.endpoint = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new webstreamer.Endpoint).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.LiveStreamCreate.startLiveStreamCreate = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} pipelineOffset
 */
webstreamer.LiveStreamCreate.addPipeline = function(builder, pipelineOffset) {
  builder.addFieldOffset(0, pipelineOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} endpointOffset
 */
webstreamer.LiveStreamCreate.addEndpoint = function(builder, endpointOffset) {
  builder.addFieldOffset(1, endpointOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.LiveStreamCreate.endLiveStreamCreate = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.LiveStreamDestroy = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.LiveStreamDestroy}
 */
webstreamer.LiveStreamDestroy.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.LiveStreamDestroy=} obj
 * @returns {webstreamer.LiveStreamDestroy}
 */
webstreamer.LiveStreamDestroy.getRootAsLiveStreamDestroy = function(bb, obj) {
  return (obj || new webstreamer.LiveStreamDestroy).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.LiveStreamDestroy.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.LiveStreamDestroy.startLiveStreamDestroy = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
webstreamer.LiveStreamDestroy.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.LiveStreamDestroy.endLiveStreamDestroy = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.LiveStreamAddEndpoint = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.LiveStreamAddEndpoint}
 */
webstreamer.LiveStreamAddEndpoint.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.LiveStreamAddEndpoint=} obj
 * @returns {webstreamer.LiveStreamAddEndpoint}
 */
webstreamer.LiveStreamAddEndpoint.getRootAsLiveStreamAddEndpoint = function(bb, obj) {
  return (obj || new webstreamer.LiveStreamAddEndpoint).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.LiveStreamAddEndpoint.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {webstreamer.Endpoint=} obj
 * @returns {webstreamer.Endpoint|null}
 */
webstreamer.LiveStreamAddEndpoint.prototype.endpoint = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new webstreamer.Endpoint).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.LiveStreamAddEndpoint.startLiveStreamAddEndpoint = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
webstreamer.LiveStreamAddEndpoint.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} endpointOffset
 */
webstreamer.LiveStreamAddEndpoint.addEndpoint = function(builder, endpointOffset) {
  builder.addFieldOffset(1, endpointOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.LiveStreamAddEndpoint.endLiveStreamAddEndpoint = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.LiveStreamAddEndpoints = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.LiveStreamAddEndpoints}
 */
webstreamer.LiveStreamAddEndpoints.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.LiveStreamAddEndpoints=} obj
 * @returns {webstreamer.LiveStreamAddEndpoints}
 */
webstreamer.LiveStreamAddEndpoints.getRootAsLiveStreamAddEndpoints = function(bb, obj) {
  return (obj || new webstreamer.LiveStreamAddEndpoints).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.LiveStreamAddEndpoints.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {webstreamer.Endpoint=} obj
 * @returns {webstreamer.Endpoint}
 */
webstreamer.LiveStreamAddEndpoints.prototype.endpoints = function(index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new webstreamer.Endpoint).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
webstreamer.LiveStreamAddEndpoints.prototype.endpointsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.LiveStreamAddEndpoints.startLiveStreamAddEndpoints = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
webstreamer.LiveStreamAddEndpoints.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} endpointsOffset
 */
webstreamer.LiveStreamAddEndpoints.addEndpoints = function(builder, endpointsOffset) {
  builder.addFieldOffset(1, endpointsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
webstreamer.LiveStreamAddEndpoints.createEndpointsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
webstreamer.LiveStreamAddEndpoints.startEndpointsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.LiveStreamAddEndpoints.endLiveStreamAddEndpoints = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.LiveStreamRemoveEndpoint = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.LiveStreamRemoveEndpoint}
 */
webstreamer.LiveStreamRemoveEndpoint.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.LiveStreamRemoveEndpoint=} obj
 * @returns {webstreamer.LiveStreamRemoveEndpoint}
 */
webstreamer.LiveStreamRemoveEndpoint.getRootAsLiveStreamRemoveEndpoint = function(bb, obj) {
  return (obj || new webstreamer.LiveStreamRemoveEndpoint).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.LiveStreamRemoveEndpoint.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.LiveStreamRemoveEndpoint.prototype.endpointId = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.LiveStreamRemoveEndpoint.startLiveStreamRemoveEndpoint = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
webstreamer.LiveStreamRemoveEndpoint.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} endpointIdOffset
 */
webstreamer.LiveStreamRemoveEndpoint.addEndpointId = function(builder, endpointIdOffset) {
  builder.addFieldOffset(1, endpointIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.LiveStreamRemoveEndpoint.endLiveStreamRemoveEndpoint = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.LiveStreamRemoveEndpoints = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.LiveStreamRemoveEndpoints}
 */
webstreamer.LiveStreamRemoveEndpoints.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.LiveStreamRemoveEndpoints=} obj
 * @returns {webstreamer.LiveStreamRemoveEndpoints}
 */
webstreamer.LiveStreamRemoveEndpoints.getRootAsLiveStreamRemoveEndpoints = function(bb, obj) {
  return (obj || new webstreamer.LiveStreamRemoveEndpoints).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.LiveStreamRemoveEndpoints.prototype.id = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
webstreamer.LiveStreamRemoveEndpoints.prototype.endpointIds = function(index, optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
webstreamer.LiveStreamRemoveEndpoints.prototype.endpointIdsLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.LiveStreamRemoveEndpoints.startLiveStreamRemoveEndpoints = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} idOffset
 */
webstreamer.LiveStreamRemoveEndpoints.addId = function(builder, idOffset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} endpointIdsOffset
 */
webstreamer.LiveStreamRemoveEndpoints.addEndpointIds = function(builder, endpointIdsOffset) {
  builder.addFieldOffset(1, endpointIdsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
webstreamer.LiveStreamRemoveEndpoints.createEndpointIdsVector = function(builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
webstreamer.LiveStreamRemoveEndpoints.startEndpointIdsVector = function(builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.LiveStreamRemoveEndpoints.endLiveStreamRemoveEndpoints = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
webstreamer.LiveStreamError = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {webstreamer.LiveStreamError}
 */
webstreamer.LiveStreamError.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {webstreamer.LiveStreamError=} obj
 * @returns {webstreamer.LiveStreamError}
 */
webstreamer.LiveStreamError.getRootAsLiveStreamError = function(bb, obj) {
  return (obj || new webstreamer.LiveStreamError).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
webstreamer.LiveStreamError.prototype.code = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
webstreamer.LiveStreamError.prototype.reason = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
webstreamer.LiveStreamError.startLiveStreamError = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} code
 */
webstreamer.LiveStreamError.addCode = function(builder, code) {
  builder.addFieldInt8(0, code, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} reasonOffset
 */
webstreamer.LiveStreamError.addReason = function(builder, reasonOffset) {
  builder.addFieldOffset(1, reasonOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
webstreamer.LiveStreamError.endLiveStreamError = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
webstreamer.LiveStreamError.finishLiveStreamErrorBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.webstreamer = webstreamer;
